Import('baseEnv', 'debugEnv', 'releaseEnv', 'buildInfo', 'axiomLib', 'axImageLoaderLib', 'spirvCrossLib', 'axModelLoaderLib')

def createVcprojUserFile(target, source, env):
    userFilePath = str(target[0]) + '.user'

    xmlContent = """<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <LocalDebuggerWorkingDirectory>$(TargetDir)</LocalDebuggerWorkingDirectory>
    <DebuggerFlavor>WindowsLocalDebugger</DebuggerFlavor>
  </PropertyGroup>
</Project>"""

    with open(userFilePath, 'w') as file:
        file.write(xmlContent.strip())

silentUserFileAction = Action(createVcprojUserFile, None)

from SCons.Script import Dir, Return

platform = buildInfo['platform']
architecture = buildInfo['architecture']
compiler = buildInfo['compiler']
config = buildInfo['config']
configName = config.capitalize()
vsproj = buildInfo['vsproj']

localEnv = (debugEnv if config.lower() == 'debug' else releaseEnv).Clone()

coreSources = Glob('Source/*.cpp')
coreSources += Glob('Source/*/*.cpp')

platformMap = {
    'windows': {'define': 'AX_PLATFORM_WINDOWS', 'path': 'Source/Platform/Windows/*.cpp'},
    'linux': {'define': 'AX_PLATFORM_LINUX', 'path': 'Source/Platform/Linux/*.cpp'},
    'macos': {'define': 'AX_PLATFORM_MACOS', 'path': 'Source/Platform/MacOS/*.cpp'}
}

key = next((k for k in platformMap if platform.startswith(k)), None)

localEnv.Append(
    CPPPATH=[
        Dir('#/Theorem/Source'),
        Dir('#/Axiom/Source'),
    ],
    LIBPATH=[
        Dir(f'#/Bin/{configName}/Axiom'),
        Dir(f'#/Bin/{configName}/AxImageLoader'),
        Dir(f'#/Bin/{configName}/SpirvCross'),
        Dir(f'#/Bin/{configName}/AxModelLoader')
    ],
    CPPDEFINES=[platformMap[key]['define']] if key else []
)

localEnv.Prepend(LIBS=[axiomLib, axImageLoaderLib, spirvCrossLib, axModelLoaderLib])

theoremApp = localEnv.Program(f'#Bin/{configName}/Theorem/Theorem', coreSources)

theoremProject = None
if vsproj:
    theoremSources = Glob('Source/*.cpp') + Glob('Source/*/*.cpp')
    theoremHeaders = Glob('Source/*.h') + Glob('Source/*/*.h')
    localEnv['CPPPATH'] = [Dir(path) for path in localEnv['CPPPATH']]

    theoremProject = localEnv.MSVSProject(
        target='#/Theorem/Theorem' + localEnv['MSVSPROJECTSUFFIX'],
        srcs=[str(f) for f in theoremSources],
        incs=[str(f) for f in theoremHeaders],
        buildtarget=theoremApp,
        runfile=theoremApp,
        variant=[f'{configName}|x64'],
        auto_build_solution=0
    )

localEnv.AddPostAction(theoremProject, silentUserFileAction)
Return('theoremApp', 'theoremProject')
