// This file is auto-generated by Reflection.py. Do not edit manually.

#include "ComponentReflection.h"

#include "CameraComponent.h"
#include "DirectionalLightComponent.h"
#include "MeshComponent.h"
#include "PhysicsComponent.h"
#include "Sprite2DComponent.h"
#include "TagComponent.h"
#include "TransformComponent.h"

namespace Axiom {
    std::unordered_map<std::type_index, ComponentInfo> ComponentReflection::componentRegistry;

    void ComponentReflection::init() {
        ComponentInfo info;

        // Registering MeshComponent from Source/Scene/Components/MeshComponent.h
        info.name = "MeshComponent";
        info.size = sizeof(MeshComponent);
        info.fields = {
            {"meshId", FieldType::AssetHandle, offsetof(MeshComponent, meshId), {}, Axiom::AssetType::Mesh},
        };
        componentRegistry[std::type_index(typeid(MeshComponent))] = info;

        // Registering CameraComponent from Source/Scene/Components/CameraComponent.h
        info.name = "CameraComponent";
        info.size = sizeof(CameraComponent);
        info.fields = {
            {"isMainCamera", FieldType::Bool, offsetof(CameraComponent, isMainCamera), {}, Axiom::AssetType::None},
            {"isFixedAspectRatio", FieldType::Bool, offsetof(CameraComponent, isFixedAspectRatio), {}, Axiom::AssetType::None},
        };
        componentRegistry[std::type_index(typeid(CameraComponent))] = info;

        // Registering TagComponent from Source/Scene/Components/TagComponent.h
        info.name = "TagComponent";
        info.size = sizeof(TagComponent);
        info.fields = {
            {"tag", FieldType::String, offsetof(TagComponent, tag), {}, Axiom::AssetType::None},
        };
        componentRegistry[std::type_index(typeid(TagComponent))] = info;

        // Registering Sprite2DComponent from
        // Source/Scene/Components/Sprite2DComponent.h
        info.name = "Sprite2DComponent";
        info.size = sizeof(Sprite2DComponent);
        info.fields = {
            {"textureId", FieldType::AssetHandle, offsetof(Sprite2DComponent, textureId), {}, Axiom::AssetType::Texture},
            {"addressMode",
             FieldType::Enum,
             offsetof(Sprite2DComponent, addressMode),
             {"Repeat", "MirroredRepeat", "ClampToEdge", "ClampToBorder"},
             Axiom::AssetType::None},
            {"filterMode", FieldType::Enum, offsetof(Sprite2DComponent, filterMode), {"Linear", "Nearest"}, Axiom::AssetType::None},
            {"color", FieldType::Color, offsetof(Sprite2DComponent, color), {}, Axiom::AssetType::None},
        };
        componentRegistry[std::type_index(typeid(Sprite2DComponent))] = info;

        // Registering DirectionalLightComponent from
        // Source/Scene/Components/DirectionalLightComponent.h
        info.name = "DirectionalLightComponent";
        info.size = sizeof(DirectionalLightComponent);
        info.fields = {
            {"color", FieldType::Color, offsetof(DirectionalLightComponent, color), {}, Axiom::AssetType::None},
            {"intensity", FieldType::Float, offsetof(DirectionalLightComponent, intensity), {}, Axiom::AssetType::None},
        };
        componentRegistry[std::type_index(typeid(DirectionalLightComponent))] = info;

        // Registering PhysicsComponent from
        // Source/Scene/Components/PhysicsComponent.h
        info.name = "PhysicsComponent";
        info.size = sizeof(PhysicsComponent);
        info.fields = {
            {"velocity", FieldType::Vec3, offsetof(PhysicsComponent, velocity), {}, Axiom::AssetType::None},
            {"acceleration", FieldType::Vec3, offsetof(PhysicsComponent, acceleration), {}, Axiom::AssetType::None},
        };
        componentRegistry[std::type_index(typeid(PhysicsComponent))] = info;

        // Registering TransformComponent from
        // Source/Scene/Components/TransformComponent.h
        info.name = "TransformComponent";
        info.size = sizeof(TransformComponent);
        info.fields = {
            {"position", FieldType::Vec3, offsetof(TransformComponent, position), {}, Axiom::AssetType::None},
            {"rotation", FieldType::Vec3, offsetof(TransformComponent, rotation), {}, Axiom::AssetType::None},
            {"scale", FieldType::Vec3, offsetof(TransformComponent, scale), {}, Axiom::AssetType::None},
        };
        componentRegistry[std::type_index(typeid(TransformComponent))] = info;
    }

    void ComponentReflection::addComponent(Entity entity, const std::string& componentType, void* componentData) {
        if (componentType == "MeshComponent") {
            if (componentData) {
                MeshComponent* comp = static_cast<MeshComponent*>(componentData);
                entity.addComponent(*comp);
            } else {
                entity.addComponent<MeshComponent>({});
            }
            return;
        }
        if (componentType == "CameraComponent") {
            if (componentData) {
                CameraComponent* comp = static_cast<CameraComponent*>(componentData);
                entity.addComponent(*comp);
            } else {
                entity.addComponent<CameraComponent>({});
            }
            return;
        }
        if (componentType == "TagComponent") {
            if (componentData) {
                TagComponent* comp = static_cast<TagComponent*>(componentData);
                entity.addComponent(*comp);
            } else {
                entity.addComponent<TagComponent>({});
            }
            return;
        }
        if (componentType == "Sprite2DComponent") {
            if (componentData) {
                Sprite2DComponent* comp = static_cast<Sprite2DComponent*>(componentData);
                entity.addComponent(*comp);
            } else {
                entity.addComponent<Sprite2DComponent>({});
            }
            return;
        }
        if (componentType == "DirectionalLightComponent") {
            if (componentData) {
                DirectionalLightComponent* comp = static_cast<DirectionalLightComponent*>(componentData);
                entity.addComponent(*comp);
            } else {
                entity.addComponent<DirectionalLightComponent>({});
            }
            return;
        }
        if (componentType == "PhysicsComponent") {
            if (componentData) {
                PhysicsComponent* comp = static_cast<PhysicsComponent*>(componentData);
                entity.addComponent(*comp);
            } else {
                entity.addComponent<PhysicsComponent>({});
            }
            return;
        }
        if (componentType == "TransformComponent") {
            if (componentData) {
                TransformComponent* comp = static_cast<TransformComponent*>(componentData);
                entity.addComponent(*comp);
            } else {
                entity.addComponent<TransformComponent>({});
            }
            return;
        }
    }

} // namespace Axiom
